#DataSource Config
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bli?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: he2002258


  redis:
    host: 127.0.0.1
    port: 6379
    password:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 8086

rocketmq:
  name:
    server:
      address: 127.0.0.1:9876

fdfs:
  tracker-list: 192.168.189.128:22122

